### ISSUE TITLE
How to pass additional arguments to objective function

### ISSUE THREAD

**Issue by navid-hoseini** [stephenbeckr/L-BFGS-B-C#4]
Hello, 
First of all thank you for your nice L-BFGS-B wrapper. The first argument of function lbfgsb is fcn which is the function that computes the objective function value and gradients. Input argument to fcn is x which is the vector of parameters to be optimised. I need to send additional arguments to fcn. Could you please tell me how I can do this. I tried to use varargin in input arguments of lbfgsb and then use varargin as input to callF in line 199 :
[f,g] = callF(x, varargin{1}, varargin{2});
but varargin is already used in lbfgs code so it is not possible to use varargin like what I have in mind. Could you please point me in the right direction? Thank you in advance.

Best regards,
Navid

**Comment by stephenbeckr** [comment]
Hi Navid,
  You can use an anonymous function. Suppose you have a function implemented like

    `function [f,g] = myGradientFunction( x, parameter1, parameter 2)`

then give the L-BFGS-B wrapper a function handle

    `f = @(x) myGradientFunction( x, parameter1, parameter2)`

So that `f` is now a function of `x` only.

See https://blogs.mathworks.com/loren/2012/08/29/thoughts-about-anonymous-functions/
e.g., where she goes to `myline = @(x) straightline(x,m,b);` as an example.

Best,
Stephen

**Comment by navid-hoseini** [comment]
Thank you for your reply. It really helped!
